export const defaultTheme = {
  colors: {
    primary: '#5658E9',
    secondary: '#DD1E88',
    primaryGradient: '#7BC3FF',
    secondaryGradient: '#5658E9',
    darkText: '#343434',
    lightText: '#676767',
    background: '#ffffff',
    container: '#293347',
    lightGrey: '#F8F8F8',
    inputBorder: '#d7d7d7',
    successLight: '#81ff00',
    success: '#499200',
    warn: '#fffc00',
    error: '#ff0000',
  },
  font: {
    family: {
      base: `"Open Sans","Arial", "Helvetica", "sans-serif"`,
      headerReg: `"Brandon", "Arial", "Helvetica", "sans-serif"`,
      headerMed: `"Brandon Med", "Arial", "Helvetica", "sans-serif"`,
      headerBold: ` "Brandon Bold", "Arial", "Helvetica", "sans-serif"`,
    },
    weight: {
      regular: 400,
      medium: 500,
      semiBold: 600,
      bold: 700,
    },
  },
  boxShadow: {
    regular: '0 0.2rem 0.7rem rgba(0, 0, 0, 0.1)',
  },
  radius: {
    sm: '0.4rem',
    md: '0.8rem',
    lg: '1.2rem',
    xl: '1.6rem',
  },
  screen: {
    xsmall: '340px',
    small: '481px',
    medsmall: '600px',
    medium: '769px',
    large: '1025px',
    xlarge: '1199px',
    xxlarge: '1500px',
  },
}
